name: ci

on:
  push:
    paths-ignore:
      - "**.md"
      - "LICENSE"
      - "NOTICE"

jobs:
  test:
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        node: ["18", "20", "22"]
        typescript: ["5.5", "5.6", "5.7"]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
      - uses: pnpm/action-setup@v4
      - run: pnpm --version
      - run: pnpm install
      - run: pnpm add -E -D typescript@${{ matrix.typescript }} -w
      - run: pnpm run build
      - run: pnpm run lint
      - run: pnpm run check
      - run: pnpm run test
      - name: Slack Notification
        if: failure()
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_CHANNEL: sora-js-sdk
          SLACK_COLOR: danger
          SLACK_TITLE: Failure test
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
