name: e2e-test

on:
  push:
    branches:
      - develop
      - feature/*
    paths-ignore:
      - "**.md"
      - "LICENSE"
      - "NOTICE"
  schedule:
    # UTC 時間で毎日 2:00 (JST で 11:00) に実行、月曜日から金曜日
    - cron: "0 2 * * 1-5"

jobs:
  e2e-test:
    timeout-minutes: 20
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        node: ["18", "20", "22"]
        # browser: ["chromium", "firefox", "webkit"]
        browser: ["chromium"]
    env:
      TEST_SIGNALING_URL: ${{ secrets.TEST_SIGNALING_URL }}
      TEST_WHIP_ENDPOINT_URL: ${{ secrets.TEST_WHIP_ENDPOINT_URL }}
      TEST_WHEP_ENDPOINT_URL: ${{ secrets.TEST_WHEP_ENDPOINT_URL }}
      TEST_CHANNEL_ID_PREFIX: ${{ secrets.TEST_CHANNEL_ID_PREFIX }}
      TEST_API_URL: ${{ secrets.TEST_API_URL }}
      TEST_SECRET_KEY: ${{ secrets.TEST_SECRET_KEY }}
    steps:
      - uses: actions/checkout@v4
      - uses: tailscale/github-action@v2
        with:
          oauth-client-id: ${{ secrets.TS_OAUTH_CLIENT_ID }}
          oauth-secret: ${{ secrets.TS_OAUTH_SECRET }}
          tags: tag:ci
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
      - uses: pnpm/action-setup@v4
      - run: pnpm --version
      - run: pnpm install
      - run: pnpm run build
      - run: pnpm exec playwright install ${{ matrix.browser }} --with-deps
      - run: pnpm exec playwright test --project=${{ matrix.browser }}
        env:
          VITE_TEST_CHANNEL_ID_SUFFIX: _${{ matrix.node }}
      # - uses: actions/upload-artifact@v4
      #   if: always()
      #   with:
      #     name: playwright-report
      #     path: playwright-report/
      #     retention-days: 30

  # slack_notify_succeeded:
  #   needs: [e2e-test]
  #   runs-on: ubuntu-24.04
  #   if: success()
  #   steps:
  #     - name: Slack Notification
  #       if: success()
  #       uses: rtCamp/action-slack-notify@v2
  #       env:
  #         SLACK_CHANNEL: sora-js-sdk
  #         SLACK_COLOR: good
  #         SLACK_TITLE: Succeeded
  #         SLACK_ICON_EMOJI: ":star-struck:"
  #         SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
  slack_notify_failed:
    needs: [e2e-test]
    runs-on: ubuntu-24.04
    if: failure()
    steps:
      - name: Slack Notification
        if: failure()
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_CHANNEL: sora-js-sdk
          SLACK_COLOR: danger
          SLACK_TITLE: Failed
          SLACK_ICON_EMOJI: ":japanese_ogre:"
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
